"""Create 5 new skill scaffolds per UTC day from a rotating template catalog.

Skill directories use stable slugs only (for example `sales-call-objection-clusterer`).
Each run picks five templates that are not already present in `skills/`.

When the catalog is exhausted, new templates are generated by:
1. Optional LLM API (GROQ_API_KEY or OPENAI_API_KEY), then
2. Deterministic word-bank combinations (no API required).
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
SAMPLES_DIR = ROOT / "samples"
TEMPLATES_FILE = ROOT / "scripts" / "skill_templates.json"

DOMAINS = [
    "api",
    "billing",
    "support",
    "security",
    "release",
    "analytics",
    "ops",
    "growth",
    "data",
    "infra",
    "product",
    "sales",
    "finance",
    "privacy",
    "identity",
    "catalog",
    "pipeline",
    "partner",
    "mobile",
    "cloud",
]

OBJECTS = [
    "quota",
    "ticket",
    "policy",
    "incident",
    "funnel",
    "contract",
    "schema",
    "latency",
    "cost",
    "entitlement",
    "alert",
    "cohort",
    "workflow",
    "inventory",
    "audit",
    "retention",
    "rollout",
    "handoff",
    "sla",
    "dependency",
    "webhook",
    "forecast",
    "budget",
    "usage",
    "migration",
    "access",
    "consent",
    "experiment",
    "backlog",
    "dashboard",
]

ACTIONS = [
    "analyzer",
    "auditor",
    "tracker",
    "ranker",
    "planner",
    "checker",
    "explainer",
    "optimizer",
    "detector",
    "summarizer",
    "triager",
    "mapper",
    "monitor",
    "linter",
    "builder",
]


@dataclass(frozen=True)
class SkillTemplate:
    slug: str
    title: str
    description: str


def load_templates() -> list[SkillTemplate]:
    if not TEMPLATES_FILE.exists():
        return []
    with open(TEMPLATES_FILE) as f:
        data = json.load(f)
    return [SkillTemplate(**item) for item in data]


def save_templates(templates: list[SkillTemplate]) -> None:
    data = [{"slug": t.slug, "title": t.title, "description": t.description} for t in templates]
    with open(TEMPLATES_FILE, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


def title_from_slug(slug: str) -> str:
    return " ".join(part.capitalize() for part in slug.split("-"))


def description_from_slug(slug: str) -> str:
    readable = slug.replace("-", " ")
    return f"Vendor-neutral skill to {readable} and produce prioritized, actionable findings."


def known_slugs() -> set[str]:
    return {template.slug for template in load_templates()} | existing_slugs()


def generate_deterministic_templates(count: int = 5) -> list[SkillTemplate]:
    """Create unique templates from domain/object/action combinations."""
    used = known_slugs()
    day_key = datetime.now(timezone.utc).strftime("%Y%m%d")
    start = sum(ord(char) for char in day_key) % (len(DOMAINS) * len(OBJECTS) * len(ACTIONS))
    total = len(DOMAINS) * len(OBJECTS) * len(ACTIONS)
    created: list[SkillTemplate] = []

    for offset in range(total):
        if len(created) >= count:
            break
        index = (start + offset) % total
        domain = DOMAINS[index % len(DOMAINS)]
        object_name = OBJECTS[(index // len(DOMAINS)) % len(OBJECTS)]
        action = ACTIONS[(index // (len(DOMAINS) * len(OBJECTS))) % len(ACTIONS)]
        slug = f"{domain}-{object_name}-{action}"
        if slug in used:
            continue
        used.add(slug)
        created.append(
            SkillTemplate(
                slug=slug,
                title=title_from_slug(slug),
                description=description_from_slug(slug),
            )
        )

    if created:
        print(f"Generated {len(created)} new skill templates via deterministic catalog.")
    else:
        print("Deterministic catalog could not find unused template combinations.")
    return created


def generate_llm_templates(count: int = 5) -> list[SkillTemplate]:
    """Generate new skill templates using Groq or OpenAI when configured."""
    api_key = os.environ.get("GROQ_API_KEY") or os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return []

    try:
        import openai
    except ImportError:
        print("Warning: openai package not installed. Run: pip install openai")
        return []

    groq_key = os.environ.get("GROQ_API_KEY")
    if groq_key:
        client = openai.OpenAI(api_key=groq_key, base_url="https://api.groq.com/openai/v1")
        model = "llama-3.3-70b-versatile"
    else:
        client = openai.OpenAI(api_key=api_key)
        model = "gpt-4o-mini"

    existing_slugs_set = known_slugs()
    prompt = f"""Generate {count} new vendor-neutral skill templates for an AI agent skills catalog.

Each template should have:
- slug: a kebab-case identifier (e.g., "api-rate-limit-analyzer")
- title: a human-readable title (e.g., "API Rate Limit Analyzer")
- description: a concise description starting with "Vendor-neutral skill to..."

Avoid these existing slugs: {', '.join(sorted(existing_slugs_set))}

Return ONLY valid JSON in this exact format:
[
  {{"slug": "example-slug", "title": "Example Title", "description": "Vendor-neutral skill to..."}},
  ...
]
"""

    try:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
        )
        content = (response.choices[0].message.content or "").strip()
        if content.startswith("```"):
            content = content.split("\n", 1)[-1]
            if content.endswith("```"):
                content = content.rsplit("```", 1)[0]
            content = content.strip()

        new_data = json.loads(content)
        unique_templates = []
        for item in new_data:
            slug = str(item.get("slug", "")).strip().lower()
            if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug):
                continue
            if slug in existing_slugs_set:
                continue
            title = str(item.get("title") or title_from_slug(slug)).strip()
            description = str(item.get("description") or description_from_slug(slug)).strip()
            unique_templates.append(SkillTemplate(slug=slug, title=title, description=description))
            existing_slugs_set.add(slug)

        if unique_templates:
            print(f"Generated {len(unique_templates)} new skill templates via {model}.")
        return unique_templates
    except Exception as exc:
        print(f"Error generating templates via LLM: {exc}")
        return []


def generate_new_templates(count: int = 5) -> list[SkillTemplate]:
    templates = generate_llm_templates(count)
    if len(templates) >= count:
        return templates[:count]
    needed = count - len(templates)
    print("Falling back to deterministic template generation...")
    templates.extend(generate_deterministic_templates(needed))
    return templates


def render_skill_md(skill_name: str, description: str) -> str:
    return f"""---
name: {skill_name}
description: {description}
---

## Purpose

Use this skill to process structured input and produce a concise, actionable report.

## Input

- JSON object or CSV rows with the relevant business signals.

## Output

- Structured JSON summary with findings and recommendations.
"""


def render_readme(skill_name: str, title: str) -> str:
    return f"""# {title}

Reference implementation for `{skill_name}`.

## Run

```bash
python run.py --input ../../samples/{skill_name}/input.json --output ../../samples/{skill_name}/output.json
```
"""


def render_python() -> str:
    return '''"""Reference implementation scaffold for a generated skill.""" 

from __future__ import annotations

import argparse
import json
from pathlib import Path


def run(payload: dict) -> dict:
    return {
        "status": "ok",
        "summary": "Generated skill scaffold executed successfully.",
        "input_keys": sorted(payload.keys()),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)
    payload = json.loads(input_path.read_text())
    result = run(payload)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(result, indent=2) + "\\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def existing_slugs() -> set[str]:
    return {
        child.name
        for child in SKILLS_DIR.iterdir()
        if child.is_dir() and (child / "SKILL.md").exists()
    }


def available_templates() -> list[SkillTemplate]:
    present = existing_slugs()
    return [template for template in load_templates() if template.slug not in present]


def daily_selection(templates: list[SkillTemplate], day_key: str, count: int) -> list[SkillTemplate]:
    if not templates:
        return []
    start = sum(ord(char) for char in day_key) % len(templates)
    selected: list[SkillTemplate] = []
    for offset in range(len(templates)):
        if len(selected) >= count:
            break
        selected.append(templates[(start + offset) % len(templates)])
    return selected


def create_skill(template: SkillTemplate) -> bool:
    skill_name = template.slug
    skill_dir = SKILLS_DIR / skill_name
    if skill_dir.exists():
        return False

    sample_dir = SAMPLES_DIR / skill_name
    skill_dir.mkdir(parents=True, exist_ok=True)
    sample_dir.mkdir(parents=True, exist_ok=True)

    (skill_dir / "SKILL.md").write_text(render_skill_md(skill_name, template.description))
    (skill_dir / "README.md").write_text(render_readme(skill_name, template.title))
    (skill_dir / "run.py").write_text(render_python())
    (sample_dir / "input.json").write_text(
        '{"source":"daily-generator","skill":"%s"}\n' % skill_name
    )
    return True


def ensure_candidates(count: int) -> list[SkillTemplate]:
    candidates = available_templates()
    if candidates:
        return candidates

    print("No templates available. Attempting to generate new ones...")
    new_templates = generate_new_templates(max(count, 20))
    if not new_templates:
        return []

    save_templates(load_templates() + new_templates)
    return available_templates()


def generate(count: int = 5) -> int:
    day_key = datetime.now(timezone.utc).strftime("%Y%m%d")
    candidates = ensure_candidates(count)

    if not candidates:
        print(
            "Created 0 skill(s). Could not find or generate unused skill templates."
        )
        return 0

    created = 0
    for template in daily_selection(candidates, day_key, count):
        if create_skill(template):
            created += 1
            print(f"Created {template.slug}")

    remaining = len(available_templates())
    if created == 0:
        print(f"Created 0 skill(s) on {day_key}. No new skills were added.")
    elif created < count:
        print(
            f"Created {created} skill(s) on {day_key}. "
            f"{remaining} template(s) remain queued in the catalog."
        )
    else:
        print(f"Created {created} skill(s) on {day_key}.")
    return created


if __name__ == "__main__":
    raise SystemExit(0 if generate(5) >= 5 else 1)
